/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'navy-deep': '#020C1B',
        'on-secondary-container': '#fefcff',
        outline: '#75777e',
        'on-surface': '#191c1e',
        'surface-tint': '#515f78',
        'secondary-fixed': '#d8e2ff',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'surface-container-high': '#e6e8ea',
        'secondary-container': '#0070ea',
        'inverse-surface': '#2d3133',
        surface: '#f7f9fb',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'primary-fixed-dim': '#b9c7e4',
        'on-surface-variant': '#44474d',
        'primary-container': '#0d1c32',
        'surface-container-highest': '#e0e3e5',
        primary: '#000000',
        secondary: '#0059bb',
        error: '#ba1a1a',
        'on-tertiary-container': '#7484a7',
        'on-error-container': '#93000a',
        'surface-dim': '#d8dadc',
        'tertiary-fixed-dim': '#b6c6ed',
        tertiary: '#000000',
        'on-secondary-fixed-variant': '#004493',
        'primary-fixed': '#d6e3ff',
        'inverse-primary': '#b9c7e4',
        'glass-stroke': 'rgba(255, 255, 255, 0.1)',
        'on-primary-container': '#76849f',
        'surface-bright': '#f7f9fb',
        'secondary-fixed-dim': '#adc7ff',
        'outline-variant': '#c5c6cd',
        'on-error': '#ffffff',
        background: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-variant': '#e0e3e5',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#374767',
        'electric-blue': '#00F0FF',
        'surface-container': '#eceef0',
        'tertiary-container': '#091b39',
        'on-secondary-fixed': '#001a41',
        'slate-gray': '#64748B',
        'on-primary-fixed': '#0d1c32',
        'on-tertiary-fixed': '#091b39',
        'on-primary-fixed-variant': '#39475f',
        'tertiary-fixed': '#d8e2ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        baseline: '8px',
        'container-max': '1280px',
        'section-gap': '120px',
        'margin-mobile': '16px',
        gutter: '24px',
      },
      fontFamily: {
        'display-lg': ['Playfair Display'],
        'label-caps': ['DM Sans'],
        'headline-md': ['Playfair Display'],
        'body-lg': ['DM Sans'],
        'body-md': ['DM Sans'],
        'display-lg-mobile': ['Playfair Display'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
